proxies:
  - name: test
    server: api.qiscus.com
    port: 443
    type: vmess
    uuid: 6fea1649-425b-4092-bf53-29792152c925
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg-lb.vhax.net
    network: ws
    ws-opts: 
      path: /sshkit/nzjxnjskanz/63588f4fd10f4/
      headers: 
        Host: sg-lb.vhax.net
    udp: true
